# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permmission',
            name='code',
            field=models.CharField(default='list', max_length=32),
        ),
    ]
